export const ADD_BOOK = 'ADD_BOOK';
export const DELETE_BOOK = 'DELETE_BOOK';
export const FETCH_FICTION_BESTSELLERS = 'FETCH_FICTION_BESTSELLERS';
export const FETCH_NONFICTION_BESTSELLERS = 'FETCH_NONFICTION_BESTSELLERS';
export const FETCH_BOOK = 'FETCH_BOOK';
export const FETCH_BOOKS = 'FETCH_BOOKS';
export const UPDATE_BOOK = 'UPDATE_BOOK';
